# Page settings

baseURL = "/"
languageCode = "en"
title = ""
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"






[params]
    author = "Richard Martin"
    description = "Richard Martin's Resume"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Richard Martin"
        tagline = "Digital Nomad & Web Developer"
        avatar = "avatar.jpeg"







    [params.contact]
        enable = true
        location = "Planet Earth"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:8652749603"
        text = "+1 (865) 274-9603"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:rich@richdmart.in"
        text = "rich@richdmart.in"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://richdmart.in"
        text = "Personal Site"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://swifte.ch"
        text = "Swiftech"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://oneresume.us"
        text = "OneResume"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "JavaScript/React"
        [[params.skills.list.items]]
        details = "Python/Java"
        [[params.skills.list.items]]
        details = "HTML/CSS"
        
        [[params.skills.list]]
        title = "Business"
        [[params.skills.list.items]]
        details = "Strategy & Development"
        [[params.skills.list.items]]
        details = "Market Research"
        [[params.skills.list.items]]
        details = "Operations"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Good time management"








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "BA in International Business"
        university = "Maryville College"
        dates = "2018 - 2021"
        [[params.education.list]]
        degree = "Studied Computer Science"
        university = "East Tennessee State University"
        dates = "2016 - 2018"








    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"








    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "English"
        level = "Native"
        [[params.languages.list]]
        name = "German"
        level = "Conversational"
        [[params.languages.list]]
        name = "Spanish"
        level = "Basic"








    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Programming"
        [[params.interests.list]]
        name = "Reading"
        [[params.interests.list]]
        name = "Running"
        [[params.interests.list]]
        name = "Guitar Playing"
        [[params.interests.list]]
        name = "Travel"
        [[params.interests.list]]
        name = "Video Games"








    [params.summary]
        enable = true
        text = "I'm Richard Martin, a recent graduate from Maryville College with a degree in International Business. I have worked in IT and Networking, as a Server in restaurants, in Marketing, and in a law firm. I currently pursue the digital nomad lifestyle, with a background in Web Development and I'm using my business skills to launch new ideas and pursue new perspectives."








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Junior Broker"
        dates = "June 2021 - August 2021"
        company = "Priority Business Brokers"
        details = "Sourced leads for business sales in a direct buyer-to-seller company style. Recommended optimizations for businesses which were in the process of acquisition by the company"
        [[params.experience.list.items]]
        details = "Cold-called business owners about sales prospects"
        [[params.experience.list.items]]
        details = "Studied businesses and recommended improvements prior to acquisition"

        [[params.experience.list]]
        title = "Runner and Clerk"
        dates = "March 2020 - May 2021"
        company = "Anderson Busby, PLLC"
        details = "Assisted in the drafting and delivery of legal documents to courts and clients. Improved filing processes and optimized otherwise long-term processes."
        [[params.experience.list.items]]
        details = "Filed of court documents, including estate documents and subpoenas"
        [[params.experience.list.items]]
        details = "Drafted legal documents for supervising attorneys"
        [[params.experience.list.items]]
        details = "Maintained an organized filesystem for quick discovery"

        [[params.experience.list]]
        title = "Server"
        dates = "May 2019 - November 2019"
        company = "Calhoun's Restaurant"
        details = "Ensured a satisfactory dining experience for guests with quick and friendly service"

        [[params.experience.list]]
        title = "Marketing Intern"
        dates = "September 2018 - May 2019"
        company = "Metz Culinary Management"
        details = "Designed marketing materials and organized promotional events to engage students on Maryville College campus"

        [[params.experience.list]]
        title = "IT Expert and Assistant Manager"
        dates = "May 2017 - August 2018"
        company = "Neighborhood Nerds"
        details = "Assisted members of the service with technical support questions and designed processes for the smooth operation of the business"

        [[params.experience.list]]
        title = "Network Technician"
        dates = "August 2016 - May 2017"
        company = "Structured Solutions, LLC"
        details = "Implemented network solutions for local businesses and configured the network for optimal performance"
        
        [[params.experience.list]]
        title = "Server"
        dates = "February 2015 - August 2016"
        company = "Dean's Restaurant & Bakery"
        details = "Ensured a satisfactory dining experience for guests with quick and friendly service"











    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "OneResume"
        meta = "Digital Resume Platform"
        tagline = "OneResume is a platform to host your resume online to bring the spotlight to you and your skills."

        [[params.projects.list]]
        title = "Swiftech"
        meta = "Tech Support & Web Development"
        tagline = "Swiftech is a technical support company which specializes in remote support and hardware repair. The company also engages in web development for small businesses and nonprofits."










    [params.information]
        enable = true

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2021 · Multinational Corporations and Private Data"








    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/richdmartin13"
        title = "richdmartin13"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/richdmartin"
        title = "richdmartin"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/richdmartin"
        title = "@richdmartin"
        [[params.social.list]]
        icon = "fab fa-instagram-square"
        url = "//instagram.com/richdmartin13"
        title = "@richdmartin13"





